#:import theme screens.theme

<HomeTab>:
    MDBoxLayout:
        orientation: "vertical"

        TopBar:
            id: topbar
            title: "NovelFetch"

        ScrollView:
            always_overscroll: False

            MDBoxLayout:
                id: content_box
                orientation: "vertical"
                adaptive_height: True
                padding: (theme.PAGE_PAD, 0, theme.PAGE_PAD, theme.PAGE_PAD)
                spacing: theme.SECTION_GAP